### ISSUE TITLE
py/demo.py critic loop exit, uncaught exception

### ISSUE THREAD

**Issue by Ganben** [Ganben/linux-basestaion#7]
[Errno 110] Connection timed out(0)
Traceback (most recent call last):
  File "demo.py", line 342, in <module>
    devices = callscanner.scan(scannerScanTime)

**Comment by Ganben** [comment]
File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 236, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 290, in _waitResp
    raise BTLEException(BTLEException.DISCONNECTED, "Device disconnected")
bluepy.btle.BTLEException: Device disconnected
